meta_product_name: "Meetsicians"
meta_title: "Meetsicians - Find hot bands in your area"
meta_description: "Find a hot band in your area, get in touch with musicians, share your skills and play dope music"
meta_image: "meta-cover.png" # should exist in `app/assets/images/`
